This jupyter notebook displays the usage of the BMI troute model. If you want to look into the source code, please refer to https://github.com/CIROH-UA/t-route/blob/EKF_Troute/src/troute-nwm/src/nwm_routing/bmi_troute.py 

In [1]:
import sys
import os

# Add the 'src' directory inside 'troute-nwm' to your Python path
sys.path.append(os.path.abspath("../../src/troute-nwm/src"))
from nwm_routing.bmi_troute import BmiTroute

In [2]:
#initializing the model
model = BmiTroute()
model.initialize(config_file="troute.yaml")

creating supernetwork connections set


2026-09-30 12:20:43,734 - root - INFO - [AbstractNetwork.py:525 - create_independent_networks]: organizing connections into reaches ...
2026-09-30 12:20:43,734 - root - INFO - [AbstractNetwork.py:682 - initial_warmstate_preprocess]: setting channel initial states ...
2026-09-30 12:20:43,737 - root - INFO - [AbstractNetwork.py:128 - assemble_forcings]: Creating a DataFrame of lateral inflow forcings ...


supernetwork connections set complete
... in 0.8919110298156738 seconds.


2026-09-30 12:20:44,449 - root - INFO - [DataAssimilation.py:77 - __init__]: NudgingDA class is Started.
2026-09-30 12:20:44,450 - root - INFO - [DataAssimilation.py:286 - __init__]: PersistenceDA class is started.
2026-09-30 12:20:44,450 - root - INFO - [DataAssimilation.py:840 - __init__]: RFCDA class is started.
2026-09-30 12:20:44,451 - root - INFO - [DataAssimilation.py:719 - __init__]: great_lake class is started.


In [3]:
#print the start date time of the model
model.get_current_datetime()

Timestamp('2022-08-22 00:00:00+0000', tz='UTC')

In [4]:
#advance the model 15 minutes into the future
model.update()

2026-09-30 12:20:44,460 - root - INFO - [__main__.py:1176 - nwm_route]: executing routing computation, with Courant evaluation metrics returned
2026-09-30 12:20:44,462 - root - INFO - [compute.py:659 - compute_nhd_routing_v02]: JIT Preprocessing time 0.0017080307006835938 seconds.
2026-09-30 12:20:44,463 - root - INFO - [compute.py:660 - compute_nhd_routing_v02]: starting Parallel JIT calculation
2026-09-30 12:20:45,936 - root - INFO - [compute.py:907 - compute_nhd_routing_v02]: PARALLEL TIME 1.4732558727264404 seconds.
2026-09-30 12:20:45,938 - root - INFO - [__main__.py:1176 - nwm_route]: executing routing computation, with Courant evaluation metrics returned
2026-09-30 12:20:45,939 - root - INFO - [compute.py:659 - compute_nhd_routing_v02]: JIT Preprocessing time 0.0009369850158691406 seconds.
2026-09-30 12:20:45,940 - root - INFO - [compute.py:660 - compute_nhd_routing_v02]: starting Parallel JIT calculation
2026-09-30 12:20:46,792 - root - INFO - [compute.py:907 - compute_nhd_rout

In [5]:
#get reaches from the model
model.get_value_ptr("reach_list")

array([2416825, 2416826, 2416827, 2416828, 2416829, 2416830, 2416831,
       2416908, 2416909, 2416910, 2416911, 2416912, 2416913, 2416914,
       2416915, 2416916, 2416917, 2416918, 2416919, 2416920, 2416921,
       2416922, 2416923, 2416924, 2416925, 2416926, 2416927, 2416928,
       2416929, 2416930, 2416931, 2416932, 2416933, 2416934, 2416935,
       2419856, 2419857, 2419858, 2419859, 2419860, 2419861, 2419862,
       2419863, 2419864, 2419865, 2419953, 2419954, 2419955, 2419956,
       2419957, 2419958, 2419959, 2419960, 2419961, 2419962, 2419963,
       2419964, 2419965, 2419966, 2419967, 2419968, 2419969, 2419970,
       2419971, 2419972, 2419973, 2419974, 2419975, 2419976, 2419977,
       2419978, 2419979, 2419980, 2419981, 2419982, 2419983, 2419984,
       2430564, 2430565, 2430566, 2430567, 2430568, 2430569, 2430570,
       2430571, 2430572, 2430573, 2430574, 2430575, 2430576, 2430577,
       2430578, 2430579, 2430580, 2430581, 2430582, 2430583, 2430584,
       2430585, 2430

In [6]:
#get discharge value from the model. the indexing is associated with the reach. 
model.get_value_ptr("discharge")

array([0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       4.2359599e-05, 1.9593244e-07, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       8.0336127e-03, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 3.7615875e-05,
       5.2714313e-08, 1.5319798e-03, 1.8437009e-04, 6.6823005e-03,
       9.4379910e-05, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       4.9602106e-02, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 5.3131972e-03,
       3.6093097e-05, 1.5834227e-01, 2.2031672e-02, 1.7614972e

In [7]:
#get k value from the model. the indexing is associated with the reach. 
model.get_value_ptr("k")

array([1.29384205e-01, 9.15601701e-02, 6.84332699e-02, 6.21039234e-02,
       1.44454064e-02, 8.85426358e-04, 4.38580886e-02, 1.23579718e-01,
       5.88414781e-02, 4.73264344e-02, 5.18343002e-02, 1.23508446e-01,
       8.68426040e-02, 5.69066405e-02, 5.37206680e-02, 9.86223072e-02,
       1.39528081e-01, 9.21907350e-02, 8.47862437e-02, 6.22174107e-02,
       7.23355561e-02, 1.05920441e-01, 1.11033581e-01, 6.94927424e-02,
       1.10379979e-01, 6.93684369e-02, 8.44845176e-02, 9.52600390e-02,
       7.10403994e-02, 9.62002501e-02, 6.29505143e-02, 6.55331537e-02,
       1.07797608e-01, 1.28806725e-01, 1.42890349e-01, 1.00197032e-01,
       9.60433781e-02, 8.39776620e-02, 7.31378123e-02, 1.32062100e-02,
       9.58913530e-04, 3.99555787e-02, 2.17729360e-02, 4.80708405e-02,
       1.34303328e-02, 1.04228340e-01, 6.99115321e-02, 7.35198334e-02,
       1.77324638e-01, 1.11529559e-01, 1.25815585e-01, 1.30539536e-01,
       1.29331708e-01, 1.04259826e-01, 1.37869522e-01, 8.81557465e-02,
      

In [8]:
#get x value from the model. the indexing is associated with the reach. 
model.get_value_ptr("x")

array([0.        , 0.        , 0.        , 0.        , 0.49999937,
       0.49999917, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.49992862, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.4999996 ,
       0.4999999 , 0.49998486, 0.49999818, 0.49978244, 0.49999884,
       0.        , 0.        , 0.        , 0.49968824, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.49997246, 0.49999982, 0.49578676, 0.49989203, 0.4999348 ,
       0.49851066, 0.        , 0.        , 0.49939197, 0.        ,
       0.4998883 , 0.49998122, 0.4999996 , 0.        , 0.49999014,
       0.        , 0.        , 0.        , 0.        , 0.     

In [9]:
#check what the current date time is
model.get_current_datetime()

Timestamp('2022-08-22 00:15:00+0000', tz='UTC')

In [10]:
#update the model using update_until for a day. the functional argument should be time in seconds
model.update_until(24*60*60)

2026-09-30 12:20:47,210 - root - INFO - [__main__.py:1176 - nwm_route]: executing routing computation, with Courant evaluation metrics returned
2026-09-30 12:20:47,211 - root - INFO - [compute.py:659 - compute_nhd_routing_v02]: JIT Preprocessing time 0.00098419189453125 seconds.
2026-09-30 12:20:47,212 - root - INFO - [compute.py:660 - compute_nhd_routing_v02]: starting Parallel JIT calculation
2026-09-30 12:20:47,666 - root - INFO - [compute.py:907 - compute_nhd_routing_v02]: PARALLEL TIME 0.45432591438293457 seconds.
2026-09-30 12:20:47,668 - root - INFO - [__main__.py:1176 - nwm_route]: executing routing computation, with Courant evaluation metrics returned
2026-09-30 12:20:47,669 - root - INFO - [compute.py:659 - compute_nhd_routing_v02]: JIT Preprocessing time 0.0008878707885742188 seconds.
2026-09-30 12:20:47,670 - root - INFO - [compute.py:660 - compute_nhd_routing_v02]: starting Parallel JIT calculation
2026-09-30 12:20:47,754 - root - INFO - [compute.py:907 - compute_nhd_routi

In [11]:
print(model.get_current_datetime())

2022-08-23 00:15:00+00:00


In [12]:
#update for 45 minutes
model.update_until(45*60)

2026-09-30 12:21:14,212 - root - INFO - [__main__.py:1176 - nwm_route]: executing routing computation, with Courant evaluation metrics returned
2026-09-30 12:21:14,214 - root - INFO - [compute.py:659 - compute_nhd_routing_v02]: JIT Preprocessing time 0.001046895980834961 seconds.
2026-09-30 12:21:14,214 - root - INFO - [compute.py:660 - compute_nhd_routing_v02]: starting Parallel JIT calculation
2026-09-30 12:21:14,305 - root - INFO - [compute.py:907 - compute_nhd_routing_v02]: PARALLEL TIME 0.09001612663269043 seconds.
2026-09-30 12:21:14,306 - root - INFO - [__main__.py:1176 - nwm_route]: executing routing computation, with Courant evaluation metrics returned
2026-09-30 12:21:14,308 - root - INFO - [compute.py:659 - compute_nhd_routing_v02]: JIT Preprocessing time 0.0009632110595703125 seconds.
2026-09-30 12:21:14,308 - root - INFO - [compute.py:660 - compute_nhd_routing_v02]: starting Parallel JIT calculation
2026-09-30 12:21:14,397 - root - INFO - [compute.py:907 - compute_nhd_rout

In [13]:
model.get_current_datetime()

Timestamp('2022-08-23 01:00:00+0000', tz='UTC')

This coding snippet below checks whether the output produced by the source code matches the output produced by the BMI model.

In [14]:
import xarray as xr
import numpy as np

output_ds = xr.open_dataset("outputs/troute_output_202208220000.nc")
feature_id = 2431095
feature_id_idx = np.where(model.get_value_ptr("reach_list")==feature_id)
discharge_value_BMI_model = model.get_value_ptr("discharge")[feature_id_idx]
discharge_value_troute_model = output_ds.sel(feature_id=feature_id, time='2022-08-23T01:00:00.000000000').flow.values
print(f"The output value produced by the troute BMI model at time step {model.get_current_datetime()} for feature_id {feature_id} is {discharge_value_BMI_model[0]}")
print(f"The output value produced by the troute source code at time step {model.get_current_datetime()} for feature_id {feature_id} is {discharge_value_troute_model}")


The output value produced by the troute BMI model at time step 2022-08-23 01:00:00+00:00 for feature_id 2431095 is 159.58912658691406
The output value produced by the troute source code at time step 2022-08-23 01:00:00+00:00 for feature_id 2431095 is 159.59268188476562
